### ISSUE TITLE
Can't save new stop

### ISSUE THREAD

**Issue by sntran** [thaoho21294/bsn_web#4]
## Steps to reproduce:

- Click the pencil button on nav bar.
- Select a point on map.
- Don't see anything happen.
- Click on "Plan"
- Enter name of the stop
- Click "Lưu"
- Nothing happens.

**Comment by thaoho21294** [comment]
oh, look strange
I'll check it again and commit.

**Comment by sntran** [comment]
Seems to be fixed.
